name: Deploy to GitHub Pages On Build Success

on:
  workflow_run:
    workflows: [NodeJS with yarn]
    types:
      - completed

jobs:
  deploy:
    permissions:
      contents: read
      pages: write
      id-token: write

    runs-on: ubuntu-latest

    timeout-minutes: 5

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/upload-artifact@v4
        id: frontend-dist
      - uses: actions/checkout@v3
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
